function atomicNumber = getAtomicNumber(elementSymbol)
% GETATOMICNUMBER Maps a chemical element symbol to its atomic number.
%
% This function provides a mapping from the chemical element symbol (e.g., 'H' for Hydrogen, 'O' for Oxygen)
% to its corresponding atomic number (e.g., 1 for Hydrogen, 8 for Oxygen).
%
% Usage:
%   atomicNumber = utils.getAtomicNumber(elementSymbol);
%
% Input:
%   elementSymbol - A string representing the chemical element symbol (case-sensitive).
%
% Output:
%   atomicNumber - The atomic number corresponding to the input element symbol.
%
% Example:
%   atomicNumber = utils.getAtomicNumber('Fe');  % Returns 26 for Iron

elementToAtomicNumberMap = containers.Map( ...
    {'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', ...
    'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', ...
    'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', ...
    'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr', ...
    'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', ...
    'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', ...
    'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', ...
    'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', ...
    'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th', ...
    'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', ...
    'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds', ...
    'Rg', 'Cn'}, ...
    num2cell(1:112));
atomicNumber = elementToAtomicNumberMap(elementSymbol);
end

